// Passenger (cPanel Node.js) entry point for Next.js standalone server
// This simply loads the standalone server.js generated by `next build`

const path = require("path");

// Set PORT for Passenger compatibility
if (!process.env.PORT) {
  process.env.PORT = "3000";
}

// Load the Next.js standalone server
require(path.join(__dirname, "server.js"));
