-- ===========================================
-- LIZGAT Hotel - Seed Data
-- Run this in phpMyAdmin AFTER schema.sql
-- ===========================================

-- 1. Admin user (password: admin123, bcrypt hash)
INSERT INTO `admin_users` (`id`, `email`, `name`, `passwordHash`, `role`, `createdAt`, `updatedAt`) VALUES
('clseed00001', 'admin@lizgathotel.com', 'Admin', '$2a$12$LJ3m4ys3Gz8y0Gv5Z0RBJePwOp2qO6UdXoOIlPbWv0yR1FQxSvKHy', 'superadmin', NOW(3), NOW(3));

-- 2. Rooms
INSERT INTO `rooms` (`id`, `slug`, `name`, `category`, `price`, `description`, `shortDescription`, `capacity`, `size`, `bedType`, `image`, `images`, `amenities`, `featured`, `isActive`, `sortOrder`, `createdAt`, `updatedAt`) VALUES
('clseed00010', 'standard-room', 'Standard Room', 'standard', 120, 'Our Standard Room offers a comfortable retreat with modern amenities, perfect for both business and leisure travelers. Enjoy a restful night''s sleep on our premium mattress, surrounded by tasteful African-inspired decor that celebrates Ghana''s rich cultural heritage.', 'A comfortable retreat with modern amenities for the discerning traveler.', 2, '28 sqm', 'Queen Bed', '/images/rooms/room-2/036.jpg', '["/images/rooms/room-2/036.jpg","/images/rooms/room-2/037.jpg","/images/rooms/room-2/038.jpg"]', '["Free Wi-Fi","Air Conditioning","Flat Screen TV","Mini Bar","Room Service","Daily Housekeeping"]', 0, 1, 0, NOW(3), NOW(3)),
('clseed00011', 'deluxe-room', 'Deluxe Room', 'deluxe', 180, 'Step into luxury with our Deluxe Room, featuring expanded living space, premium furnishings, and stunning views of Accra. The room blends contemporary comfort with authentic Ghanaian artistry, creating an unforgettable stay experience.', 'Expanded luxury with premium furnishings and city views.', 2, '38 sqm', 'King Bed', '/images/rooms/room-4/045.jpg', '["/images/rooms/room-4/045.jpg","/images/rooms/room-4/046.jpg","/images/rooms/room-4/047.jpg"]', '["Free Wi-Fi","Air Conditioning","55\\\" Smart TV","Mini Bar","Room Service","Bathrobe & Slippers","Coffee Machine","Safe Box"]', 1, 1, 1, NOW(3), NOW(3)),
('clseed00012', 'executive-suite', 'Executive Suite', 'suite', 280, 'Our Executive Suite is designed for those who demand the finest. With a separate living area, work desk, and premium bathroom amenities, this suite is perfect for extended stays or business travelers who want to unwind in style.', 'Separate living area and workspace for the executive traveler.', 3, '55 sqm', 'King Bed', '/images/rooms/room-7/055.jpg', '["/images/rooms/room-7/055.jpg","/images/rooms/room-7/056.jpg","/images/rooms/room-7/057.jpg"]', '["Free Wi-Fi","Air Conditioning","65\\\" Smart TV","Full Mini Bar","24/7 Room Service","Bathrobe & Slippers","Espresso Machine","Safe Box","Work Desk","Living Area"]', 1, 1, 2, NOW(3), NOW(3)),
('clseed00013', 'family-room', 'Family Room', 'deluxe', 220, 'Designed with families in mind, our Family Room offers generous space and thoughtful amenities for parents and children alike. Enjoy the extra room to relax while keeping the little ones entertained and comfortable.', 'Spacious comfort designed for the whole family.', 4, '48 sqm', '1 King + 2 Twin Beds', '/images/rooms/room-10/066.jpg', '["/images/rooms/room-10/066.jpg","/images/rooms/room-10/067.jpg","/images/rooms/room-10/068.jpg"]', '["Free Wi-Fi","Air Conditioning","50\\\" Smart TV","Mini Fridge","Room Service","Baby Cot Available","Game Console","Daily Housekeeping"]', 0, 1, 3, NOW(3), NOW(3)),
('clseed00014', 'presidential-suite', 'Presidential Suite', 'presidential', 450, 'The crown jewel of LIZGAT Hotel, our Presidential Suite offers unparalleled luxury across two floors. Featuring a grand living room, private dining area, and panoramic views of Accra, this suite redefines opulence. Every detail has been curated to provide an experience befitting royalty.', 'Two floors of unparalleled luxury with panoramic city views.', 4, '120 sqm', 'Super King Bed', '/images/rooms/room-11/077.jpg', '["/images/rooms/room-11/077.jpg","/images/rooms/room-11/078.jpg","/images/rooms/room-11/079.jpg"]', '["Free Wi-Fi","Climate Control","75\\\" Smart TV","Premium Mini Bar","24/7 Butler Service","Luxury Bathrobe & Slippers","Private Dining Area","Jacuzzi","Walk-in Closet","Grand Piano","Private Balcony","Espresso Machine"]', 1, 1, 4, NOW(3), NOW(3)),
('clseed00015', 'honeymoon-suite', 'Honeymoon Suite', 'suite', 350, 'Celebrate love in our exquisite Honeymoon Suite, where romance meets luxury. Rose-petal turndown service, couples'' spa treatments, and a private balcony overlooking the gardens create the perfect setting for an unforgettable romantic getaway.', 'Romance meets luxury for an unforgettable experience.', 2, '65 sqm', 'King Bed with Canopy', '/images/rooms/room-14/089.jpg', '["/images/rooms/room-14/089.jpg","/images/rooms/room-14/090.jpg","/images/rooms/room-14/091.jpg"]', '["Free Wi-Fi","Climate Control","65\\\" Smart TV","Premium Mini Bar","24/7 Room Service","Luxury Bathrobe & Slippers","Couples'' Spa Access","Jacuzzi","Rose Petal Turndown","Champagne Welcome","Private Balcony"]', 0, 1, 5, NOW(3), NOW(3));

-- 3. Amenities
INSERT INTO `amenities` (`id`, `amenityId`, `name`, `description`, `iconName`, `image`, `details`, `isActive`, `sortOrder`, `createdAt`, `updatedAt`) VALUES
('clseed00023', 'restaurant', 'Restaurant & Bar', 'Savor exquisite cuisine from our award-winning chefs, blending Ghanaian flavors with international fine dining.', 'UtensilsCrossed', '/images/restaurant/027.jpg', '["Breakfast buffet 6:30 - 10:30 AM","All-day dining restaurant","Rooftop bar with cocktails","Traditional Ghanaian cuisine","International menu","Private dining available"]', 1, 3, NOW(3), NOW(3)),
('clseed00024', 'conference', 'Conference Rooms', 'Host successful events in our versatile conference facilities equipped with the latest audiovisual technology.', 'Users', '/images/conference/001.jpg', '["3 fully equipped meeting rooms","Capacity up to 200 guests","Projector and screen","Video conferencing setup","Catering services available","Dedicated event coordinator"]', 1, 4, NOW(3), NOW(3)),
('clseed00025', 'business', 'Business Center', 'Stay productive with our fully equipped business center offering printing, faxing, and private workspaces.', 'Briefcase', '/images/reception/024.jpg', '["High-speed internet","Printing and scanning","Private meeting pods","Administrative assistance","Available 24/7","Complimentary coffee and tea"]', 1, 5, NOW(3), NOW(3)),
('clseed00027', 'wifi', 'Free High-Speed Wi-Fi', 'Stay connected throughout your stay with complimentary high-speed wireless internet access in all areas.', 'Wifi', '/images/reception/025.jpg', '["Complimentary for all guests","Available in all rooms and public areas","High-speed fiber connection","Streaming-ready speeds","Secure network","Technical support available"]', 1, 7, NOW(3), NOW(3)),
('clseed00028', 'concierge', 'Concierge Service', 'Our dedicated concierge team is available around the clock to assist with dining reservations, tours, and local experiences.', 'ConciergeBell', '/images/reception/023.jpg', '["24/7 availability","Restaurant reservations","Tour and activity booking","Transportation arrangements","Special occasion planning","Local area expertise"]', 1, 8, NOW(3), NOW(3)),
('clseed00029', 'laundry', 'Laundry Service', 'Keep your wardrobe fresh with our professional same-day laundry and dry-cleaning service.', 'WashingMachine', '/images/mart/017.jpg', '["Same-day service","Dry cleaning available","Express service","Ironing and pressing","Pickup from room","Eco-friendly detergents"]', 1, 9, NOW(3), NOW(3)),
('clseed00030', 'parking', 'Valet Parking', 'Enjoy hassle-free parking with our secure valet service, available for all hotel guests.', 'Car', '/images/environs/008.jpg', '["Complimentary for guests","Secure underground parking","24/7 valet service","EV charging stations","CCTV monitored","Easy access to lobby"]', 1, 10, NOW(3), NOW(3)),
('clseed00031', 'security', '24/7 Security', 'Your safety is our priority. Our professional security team ensures a safe and secure environment at all times.', 'ShieldCheck', '/images/environs/007.jpg', '["Round-the-clock security personnel","CCTV surveillance","Electronic key card access","In-room safe boxes","Fire safety systems","Emergency response team"]', 1, 11, NOW(3), NOW(3));

-- 4. Testimonials
INSERT INTO `testimonials` (`id`, `name`, `location`, `rating`, `text`, `avatar`, `isActive`, `sortOrder`, `createdAt`, `updatedAt`) VALUES
('clseed00040', 'Kwame Asante', 'Accra, Ghana', 5, 'An absolutely exceptional experience from check-in to check-out. The staff went above and beyond to make our anniversary celebration truly special. The Presidential Suite was breathtaking!', 'KA', 1, 0, NOW(3), NOW(3)),
('clseed00041', 'Sarah Mitchell', 'London, UK', 5, 'LIZGAT Hotel exceeded all expectations. The blend of Ghanaian hospitality with world-class service is remarkable. The dining experience was divine, and the restaurant served the best jollof rice I''ve ever tasted.', 'SM', 1, 1, NOW(3), NOW(3)),
('clseed00042', 'David Osei', 'Kumasi, Ghana', 5, 'Perfect for business travel. The conference facilities are top-notch, and the Executive Suite provided a wonderful space to relax after meetings. I''ll definitely be returning on my next trip.', 'DO', 1, 2, NOW(3), NOW(3)),
('clseed00043', 'Aisha Johnson', 'New York, USA', 5, 'What a gem in Accra! The hotel grounds are stunning, the rooms are impeccably clean, and the concierge helped us plan the most amazing tour of the city. Highly recommended for any traveler!', 'AJ', 1, 3, NOW(3), NOW(3)),
('clseed00044', 'Emmanuel Mensah', 'Cape Coast, Ghana', 5, 'We hosted our wedding reception at LIZGAT Hotel and it was absolutely magical. The event team handled everything flawlessly. Our guests are still talking about how wonderful it was!', 'EM', 1, 4, NOW(3), NOW(3)),
('clseed00045', 'Chen Wei', 'Beijing, China', 5, 'Outstanding hospitality! From the moment we arrived, we felt welcomed and valued. The attention to detail in every aspect of the hotel is impressive. A true five-star experience in Ghana.', 'CW', 1, 5, NOW(3), NOW(3));

-- 5. Gallery Images
INSERT INTO `gallery_images` (`id`, `src`, `alt`, `category`, `width`, `height`, `isActive`, `sortOrder`, `createdAt`, `updatedAt`) VALUES
('clseed00050', '/images/environs/005.jpg', 'Hotel exterior view', 'exterior', 800, 600, 1, 0, NOW(3), NOW(3)),
('clseed00051', '/images/rooms/room-2/036.jpg', 'Standard room interior', 'rooms', 800, 533, 1, 1, NOW(3), NOW(3)),
('clseed00052', '/images/environs/010.jpg', 'Hotel surroundings', 'exterior', 800, 534, 1, 2, NOW(3), NOW(3)),
('clseed00053', '/images/restaurant/027.jpg', 'Restaurant and dining area', 'dining', 800, 533, 1, 3, NOW(3), NOW(3)),
('clseed00054', '/images/conference/001.jpg', 'Conference hall setup', 'events', 800, 533, 1, 4, NOW(3), NOW(3)),
('clseed00055', '/images/rooms/room-4/045.jpg', 'Deluxe room interior', 'rooms', 800, 534, 1, 5, NOW(3), NOW(3)),
('clseed00056', '/images/reception/023.jpg', 'Hotel reception', 'exterior', 800, 533, 1, 6, NOW(3), NOW(3)),
('clseed00057', '/images/environs/012.jpg', 'Hotel entrance', 'exterior', 800, 533, 1, 7, NOW(3), NOW(3)),
('clseed00058', '/images/rooms/room-7/055.jpg', 'Executive suite living room', 'rooms', 800, 533, 1, 8, NOW(3), NOW(3)),
('clseed00059', '/images/restaurant/030.jpg', 'Bar and lounge area', 'dining', 800, 533, 1, 9, NOW(3), NOW(3)),
('clseed00060', '/images/conference/003.jpg', 'Conference room', 'events', 800, 533, 1, 10, NOW(3), NOW(3)),
('clseed00061', '/images/rooms/room-14/089.jpg', 'Honeymoon suite', 'rooms', 800, 533, 1, 11, NOW(3), NOW(3));

-- 6. Menu Items
INSERT INTO `menu_items` (`id`, `category`, `iconName`, `time`, `items`, `isActive`, `sortOrder`, `createdAt`, `updatedAt`) VALUES
('clseed00070', 'Breakfast', 'Coffee', '6:30 AM - 10:30 AM', '["Continental & Full English Breakfast","Traditional Ghanaian Breakfast (Waakye, Hausa Koko)","Fresh Tropical Fruits & Juices","Pastries & Freshly Baked Bread","Eggs to Order"]', 1, 0, NOW(3), NOW(3)),
('clseed00071', 'Lunch', 'UtensilsCrossed', '12:00 PM - 3:00 PM', '["Jollof Rice with Grilled Chicken","Grilled Tilapia with Banku","Caesar Salad with Prawns","Gourmet Burgers & Sandwiches","Chef''s Special of the Day"]', 1, 1, NOW(3), NOW(3)),
('clseed00072', 'Dinner', 'UtensilsCrossed', '6:30 PM - 10:30 PM', '["Pan-Seared Atlantic Salmon","Grilled Lamb Chops with Herbs","Fufu with Light Soup","Lobster Thermidor","Vegetarian Risotto"]', 1, 2, NOW(3), NOW(3)),
('clseed00073', 'Bar & Cocktails', 'Wine', '4:00 PM - Midnight', '["Signature Cocktails","Premium Wines & Champagne","Craft Beers & Local Brews","Mocktails & Fresh Juices","Bar Snacks & Tapas"]', 1, 3, NOW(3), NOW(3));

-- 7. Site Settings
INSERT INTO `site_settings` (`id`, `key`, `value`, `group`) VALUES
('clseed00080', 'hotel_name', 'LIZGAT Hotel', 'general'),
('clseed00081', 'hotel_tagline', 'Luxury Accommodation in Accra, Ghana', 'general'),
('clseed00082', 'address', '12 Liberation Road, Airport Residential Area, Accra, Ghana', 'contact'),
('clseed00083', 'phone', '+233 30 277 5500', 'contact'),
('clseed00084', 'whatsapp', '+233 20 123 4567', 'contact'),
('clseed00085', 'email', 'info@lizgathotel.com', 'contact'),
('clseed00086', 'reservations_email', 'reservations@lizgathotel.com', 'contact'),
('clseed00087', 'facebook', '#', 'social'),
('clseed00088', 'instagram', '#', 'social'),
('clseed00089', 'twitter', '#', 'social'),
('clseed00090', 'meta_title', 'LIZGAT Hotel | Luxury Accommodation in Accra, Ghana', 'seo'),
('clseed00091', 'meta_description', 'Experience luxury at LIZGAT Hotel in Accra, Ghana. Premium rooms, world-class dining, conference facilities, and exceptional hospitality.', 'seo');

-- 8. Page Content
INSERT INTO `page_content` (`id`, `page`, `section`, `content`, `sortOrder`, `createdAt`, `updatedAt`) VALUES
('clseed00100', 'about', 'story', '{"title":"Our Story","subtitle":"A Legacy of Luxury","text":"Founded in 2020, LIZGAT Hotel was born from a vision to create a world-class luxury destination in the heart of Accra. Our founders, inspired by Ghana''s rich cultural heritage and warm hospitality traditions, set out to build a hotel that would seamlessly blend African elegance with modern luxury.\\n\\nToday, LIZGAT Hotel stands as a testament to that vision. Every corner of our establishment reflects our commitment to excellence, from the carefully curated art pieces that adorn our walls to the locally sourced ingredients in our restaurant.","image":"/images/environs/005.jpg"}', 0, NOW(3), NOW(3)),
('clseed00101', 'about', 'values', '[{"icon":"Heart","title":"Warm Hospitality","description":"We treat every guest as family, ensuring a warm, personalized experience that reflects the best of Ghanaian hospitality."},{"icon":"Award","title":"Excellence","description":"We strive for perfection in every detail, from room preparation to dining service, maintaining the highest standards."},{"icon":"Globe","title":"Cultural Pride","description":"We celebrate Ghana''s rich culture and traditions, integrating local art, cuisine, and customs into the guest experience."},{"icon":"Shield","title":"Trust & Safety","description":"Your safety and privacy are paramount. We maintain rigorous security standards and respect guest confidentiality."}]', 1, NOW(3), NOW(3)),
('clseed00102', 'about', 'milestones', '[{"year":2020,"title":"Grand Opening","description":"LIZGAT Hotel opens its doors, welcoming its first guests with 80 luxury rooms."},{"year":2021,"title":"Spa & Wellness Launch","description":"Opening of our world-class spa featuring traditional Ghanaian treatments."},{"year":2022,"title":"Culinary Excellence Award","description":"Our restaurant receives the Ghana Hospitality Award for Best Hotel Dining."},{"year":2023,"title":"Expansion Complete","description":"Addition of 70 new rooms including the iconic Presidential Suite."},{"year":2024,"title":"5-Star Recognition","description":"Awarded official 5-star rating by the Ghana Tourism Authority."},{"year":2025,"title":"Sustainability Initiative","description":"Launch of our green initiative with solar power and water recycling systems."}]', 2, NOW(3), NOW(3)),
('clseed00103', 'home', 'hero', '{"title":"Experience Luxury in the Heart of Accra","subtitle":"Welcome to LIZGAT Hotel","description":"Where Ghanaian hospitality meets world-class luxury"}', 0, NOW(3), NOW(3)),
('clseed00104', 'home', 'welcome', '{"subtitle":"Welcome to LIZGAT","title":"A New Standard of Luxury in Ghana","text":"Nestled in the prestigious Airport Residential Area of Accra, LIZGAT Hotel redefines luxury hospitality in West Africa. Our commitment to excellence is reflected in every detail, from our meticulously designed rooms to our award-winning culinary experiences.","stats":[{"value":150,"suffix":"+","label":"Luxury Rooms"},{"value":50,"suffix":"K+","label":"Happy Guests"},{"value":15,"suffix":"+","label":"Awards Won"}]}', 1, NOW(3), NOW(3)),
('clseed00105', 'home', 'cta', '{"title":"Ready for an Unforgettable Experience?","description":"Book your stay at LIZGAT Hotel and discover the perfect blend of luxury, comfort, and Ghanaian hospitality."}', 2, NOW(3), NOW(3));
